### ISSUE TITLE
Auth Controller Tests

### ISSUE THREAD

**Issue by ryankbales** [G5/g5_authenticatable#28]
I'm working on a Fitness app for the G5 Simplifit Program.  It is hooked up to dev-auth right now.  I am trying to implement some tests for the SimplifitUsersController.  I have been using the documentation in the g5_authenticatable Readme in regards to creating user from auth.  The app then queries the database using that users email to render the appropriate profile if it exists.  I am getting the following error when I run the test tagging the context with :auth_controller:

```
 NoMethodError:
       undefined method `stub_request' for #<RSpec::ExampleGroups::SimplifitUsersController::GETIndex:0x007fb2ad3ee5b0>
```
Rails Version:  4.1.7
Ruby Version: 2.2.0p0

Here is a gist with key snippets involved:
https://gist.github.com/ryankbales/25d75764ad3762b84f66

Here is the repo if you need to look around some more:
https://github.com/ryankbales/g5-simplifit

Thanks for the help.  (Also note that I am new to writing tests.)

**Comment by maeve** [comment]
Hi @ryankbales - I think this error is occurring because the controller test helpers depend on [webmock](https://github.com/bblimke/webmock) being installed. You can install webmock in your project by adding it to the `:test` group in your Gemfile. No need to pin the version.

Thank you for pointing this out. The dependency on webmock for the test helpers is relatively new. I didn't want to add it as a direct dependency in `g5_authenticatable.gemspec`, because it isn't necessary in most environments - we only need it when running tests that use the helpers. There should at least be a note in the README, though. There's a similar undocumented dependency on [factory_girl](https://github.com/thoughtbot/factory_girl).

**Comment by ryankbales** [comment]
Thanks Maeve!  I installed webmock and the following test works like a charm!  I'll close out the issue since it's not really a bug.

```ruby
context "GET :index", :auth_controller do
    it "redirects user to their profile page when matching profile is found" do
      simplifit_user = Fabricate(:simplifit_user, user_email: user.email)
      get :index
      expect(response).to redirect_to simplifit_user_path(simplifit_user)
    end

    it "redirects to :new if authenticated user does not have a profile yet" do
      simplifit_user = Fabricate(:simplifit_user, user_email: 'not.a.matching.email@test.com')
      get :index
      expect(response).to redirect_to new_simplifit_user_path
    end

    it "sets the flash notice if authenticated user does not have a profile yet" do
      simplifit_user = Fabricate(:simplifit_user, user_email: 'not.a.matching.email@test.com')
      get :index
      expect(flash[:notice]).not_to be_blank
    end
  end

```
